### PR TITLE
chore(dep): Bump aioblescan

### PR DESCRIPTION
**Pull request by cdnninja**
Bumping aioblescan as it looks to have some fixes. Hoping this will solve my disconnect issues.

### CODE REVIEW

**Comment by cdnninja** [comment]
I have confirmed this still loads and reports my tilt after this update. I will wait a few days and report back if this solves my disconnect issues.

**Comment by thorrak** [comment]
Thank you for this!

As I recall, aioblescan minor version upgrades do not follow semantic versioning and are not necessarily backwards compatible. I'll take a look at this and see what changed.

**Comment by cdnninja** [comment]
> Thank you for this!
> 
> 
> 
> As I recall, aioblescan minor version upgrades do not follow semantic versioning and are not necessarily backwards compatible. I'll take a look at this and see what changed. 

In my testing on this version it doesn't fix my issue.  May still be worth bumping.  I made some great progress being able to replicate this though.   I'll post more to the issue thread when I get a chance.

**Comment by thorrak** [comment]
As part of the work on TiltBridge Junior I'm upgrading to the latest version of aioblescan. Closing this PR here.

Thanks again, @cdnninja - I appreciate this PR, even if it isn't ending up inside Fermentrack proper!

**Comment by cdnninja** [comment]
Sounds good.  Thanks for the update and all your work on this project!  

Great to see a round of improvement coming.

**Pull request closed without merging**
