### PR TITLE
Change to django settings to allow database to be moved to subdirectory when building docker image

### PR DESCRIPTION
**Pull request by mp-se**
These are the minimum changes I see is needed in order to get a working docker image for Fermentrack. 

If the environment variable DOCKER=yes then django will look for the database in a subdirectory. 

With this change all functions such as git upgrade will work and there is no change in user experience compared to a standard installation. There should be no real need to build new docker images unless we want to simplify upgrade of runtime components for security reasons. 

#511

### CODE REVIEW

**Comment by thorrak** [comment]
I'm happy to add this approach, but I want to tweak it slightly to match the format [here](https://github.com/thorrak/fermentrack/commit/ed5a6a4b914e03353ca37fee734bcd01d6a94e31#diff-9c8b85efb87b85b9a3085b4727a099f72ac3f710e9417eb4d4441b77158b6af5R28)

**Comment by mp-se** [comment]
Perfect, I can submit a new PR in line with your code if you want. It will make it easier to merge later. 

It mainly looks like I need to change the environment variables name/reading. Your change is a little bigger than what I have planned for. But are you fine with moving the database to a subdir called db for now and use the variable DB_DIR?

**Comment by thorrak** [comment]
Yes - Take a look at what I just merged in. It's slightly different from your code, but does the same thing.

**Comment by mp-se** [comment]
Super, looks good. As long as it does what's needed I'm happy. 

I will do some more work on my docker build process based on the egghead docker creation example that was suggested in the thread. I want to add some error handling and security so the webserver and redis is not running under root. Perhaps I will try to use the python base image as well to see if that works better than ubuntu.

**Pull request merged**
