### PR TITLE
Wifi integration

### PR DESCRIPTION
**Pull request by Kooza25**
Hello there. This is a question regarding a feature I'm not understanding if it's already there.
I currently have a brewpi arduino version running and wanted to switch over to fermentrack with that Pi and arduino. Will a brewpiless build work with my current build, communicating over wifi with my pi and having so a two chamber system?

### CODE REVIEW

**Comment by thorrak** [comment]
Closing this pull request so I don’t merge it later. Give me a few and I’ll comment on your questions.

**Comment by thorrak** [comment]
Hey there! Apologies for the delay! If you have any issues (or questions!) the best place to raise them is on the [issues](https://github.com/thorrak/fermentrack/issues) page - the pull page is how you would submit an actual change to the code, which is why I wanted to get it closed out. That said - to your questions!

You mentioned a few things in your post, so I'll try to tackle them separately. To your first note, you can absolutely switch over from your current BrewPi build to Fermentrack and have it be compatible with your Arduino running the BrewPi legacy firmware. You'll need to have the Arduino connected to the Pi running Fermentrack - but that's the same as you currently have with traditional BrewPi.

If you're looking to then add a second controller to your build that has WiFi, my recommendation would be to use an ESP8266 and build a [BrewPi-ESP8266](https://github.com/thorrak/brewpi-esp8266) controller. This is a BrewPi-compatible controller (replacing, for example, the Arduino in your current setup) that operates over WiFi. This controller would then control your second chamber, while your existing Arduino controls the first. Both controllers would speak to - and be controlled by - Fermentrack.

To your comment about BrewPiLess - BrewPiLess is a different project entirely than Fermentrack. BrewPiLess combines the controller & raspberry pi together onto an ESP8266, thereby allowing that chamber to be entirely self contained. It's a great project, and the author is someone I have great respect for - but since it replaces the Pi it isn't compatible with this specific project. If you were to go that route, you could certainly use BPL to control your second chamber, but it wouldn't show up in/be controlled by Fermentrack.

**Comment by Kooza25** [comment]
Thank you very much and my bad about the wrong place!
I badly said brewpiless but I was actually meaning that.
Very helpful and I’ll do this asap. Just to make sure, are the fermentrack controls similar to brewpi in terms of ki kp and all of those pretty stressful parameters?


Il 25 gen 2020, 23:36 +0100, John <notifications@github.com>, ha scritto:

**Comment by thorrak** [comment]
It's all the same firmware/controls, but you shouldn't need to edit/set ki, kp, etc. That should all be done behind the scenes.

Fermentrack exposes the same degree of control in a cleaner (my opinion is biased!) interface.

**Comment by lbussy** [comment]
> Fermentrack exposes the same degree of control in a cleaner (my opinion is biased!) interface

Phfft!!!  ;)

**Comment by thorrak** [comment]
Ignore @lbussy . He made poor choices. ;)

**Comment by Kooza25** [comment]
Alright, main system with arduino is set up. I don’t need to change any of the advanced settings for now, right?
Il 26 gen 2020, 01:22 +0100, John <notifications@github.com>, ha scritto:

**Comment by lbussy** [comment]
Bad decisions make better stories.

**Comment by thorrak** [comment]
> Alright, main system with arduino is set up. I don’t need to change any of the advanced settings for now, right?

Correct

**Comment by Kooza25** [comment]
Ok, everything set up. I can see the esp connected to my wifi but I cannot access its info in the dashboard. Debug says dns and connection test failed, status and cached ip passed
Il 27 gen 2020, 03:09 +0100, John <notifications@github.com>, ha scritto:

**Pull request closed without merging**
