### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by thorrak**
Thanks to @calandryll 's work, Fermentrack can now have a "dark mode" theme selected from the configuration page. This effectively adds the feature @jnr-nat requested in #507 (even though that issue was closed)

Thanks again @calandryll -- this is awesome!

### CODE REVIEW

**Comment by jnr-nat** [comment]
Awesome, Thanks, guys. Now to get it to display dark on my from my laptop..... Selected Nord Theme, and still white

**Comment by jnr-nat** [comment]
Yeah, saved reloaded, then even restarted the Pi, same result

**Comment by calandryll** [comment]
I think I know what the problem is.  I forgot to add in the settings.py file in my commit.  I'll do another pull request and that should hopefully fix it.

**Comment by thorrak** [comment]
> I think I know what the problem is. I forgot to add in the settings.py file in my commit. I'll do another pull request and that should hopefully fix it.

I thought I added the settings.py changes [on my end ](https://github.com/thorrak/fermentrack/pull/634/commits/58c70e62287de9e364ec93e6a9ee1e165b66a0d3)

**Comment by calandryll** [comment]
> > I think I know what the problem is. I forgot to add in the settings.py file in my commit. I'll do another pull request and that should hopefully fix it.
> 
> I thought I added the settings.py changes [on my end ](https://github.com/thorrak/fermentrack/pull/634/commits/58c70e62287de9e364ec93e6a9ee1e165b66a0d3)

Yep you did.  Hmm, not sure why it worked for me on my dev setup under a Ubuntu VM.

**Comment by lbussy** [comment]
"Works here."

**Comment by uSlackr** [comment]
I’m not seeing it yet.  Upgraded, set the option, saved.  It shows set to dark mode.

\\Greg

**Comment by lbussy** [comment]
> I’m not seeing it yet. Upgraded, set the option, saved. It shows set to dark mode.

HAve you used a different browser, your phone, run it in privacy mode?

**Pull request merged**
