### PR TITLE
Added external push for Grainfather

### PR DESCRIPTION
**Pull request by mp-se**
Added support for pushing gravity and temperature to Grainfather, this way it's possible to follow the fermentation on both Fermatrack and in the Grainfather app. Just made a copy of the code for brewfather with small changes.

### CODE REVIEW

**Comment by thorrak** [comment]
I honestly had no idea Grainfather supported anything like this. Thank you for sending this across! Do you happen to have a link to their API documentation so I can see what all it supports? 

One thing of note - there is another pending pull request that has a conflicting migration number - I'll regenerate the migration in this pull request to get everything to work, but it may require some finagling on your part in order to force a copy of Fermentrack that is running this branch to update once the other branch is merged in.

**Comment by mp-se** [comment]
I havent found any specific documentation for developers. But this what I found out: 

If you create an account and login there is a section called "Equipment" where fermentation devices can be added. 

They support ispindel, tilt, plaato and something they call custom. When added you get a unique URL that is your IoT endpoint. I just tried to send a standard ispindel json message to that endpoint and it worked. They only seams to use the name, temp and gravity values. 

The other thing that you need to do is to connect this device to an active brew where you get a unique number (brew session number) which is used in the json as name in my case (296033). If you use this as the name it will track the ongoing brew session. If you prefix the name with ",SG" (296033,SG) it will take the gravity from the value otherwise they will recalculate it based on the ispindel formula and angle.  

I saw the other contribution in the contributions and is fully aware that there will be a conflict. I have a copy of my database before I applied the changes so I can revert if needed. 

I can also fix the documentation for this, once I figure out how to do that.... 

Would it be of interrest to create a guide that helps to setup a development environment for fermatrack, took me a few hours to figure out the whole setup....

**Comment by thorrak** [comment]
Merging this into a new branch so I can easily tweak it to fit with the other new pushtarget

**Comment by mp-se** [comment]
I'm running the push_target branch on my latest brew and the GF integration works just fine. @thorrak

**Pull request merged**
