### PR TITLE
Allow custom graph temp range

### PR DESCRIPTION
**Pull request by uSlackr**
#502
Adds config settings and dashboard template code to allow for specifying custom y-axis range for temperature.  Allows user to see more variance in temp details/

### CODE REVIEW

**Comment by thorrak** [comment]
**First:** I'm sorry for not looking at this sooner! The past month has been nuts, and now that things are calming down a bit I'm trying to go back through and clean up some of the things that have been outstanding for a while for Fermentrack (including this PR)

**Second:** I want to think about this one a bit, and may merge it to a new branch to play with. There are two features I think need to be implemented beyond what's in this PR for this concept to work for the majority of users:

- [ ] There needs to be a flag to "toggle" this on and off. As it is, all graphs will be locked to the temp range - I'd like to allow users to still have their range be "dynamic"
- [ ] The temp range needs to update based on the temperature units of the user (C vs. F)

Also, it might warrant thinking where in the interface the toggle for this feature could sit - but that can always be added later. (While readily available features are better, I'm fine having easter eggs (like configurable graph colors) that sit in the admin)

**Comment by uSlackr** [comment]
First, life is important, it isn't in the way of Fermentrack. We all appreciate the effort on this and tour other projects. Of help more of I were smarter. Well, more familiar with the toolset. 
Appreciate your thoughts on this. I'll take a look at how to enable/disable might work. 

The change only affects the single dashboard template at the moment. For instance the gravity dashboard isn't affected at this point. 
Is there a way to check which device the dashboard is presenting?  
Should the customization be applied at the controller level rather than the dashboard?

**Comment by thorrak** [comment]
UGH. Damnit.

**Comment by uSlackr** [comment]
No worries.

\\\\ Greg
________________________________

**Pull request closed without merging**
