### PR TITLE
Map "Log1Temp" to "RoomTemp" value

### PR DESCRIPTION
**Pull request by NamelessCoder**
This PR is opened not really expecting it to be merged, but to open a discussion about handling additional temperature inputs which the official BrewPi hardware can send. It might be a good time to figure out a solution that allows adding additional temperature targets, which can be selected in the "Assign" dialog when mapping pins.

In brewpi-www there are three additional temperature sensors but no dedicated room temperature sensor. These additional targets are named `Log1Temp` through `Log3Temp`. I'm guessing `Log1Temp` is the most obvious choice for a room temperature sensor, but it would be great to support additional sensors. For example, I would like to monitor:

* Compressor motor's temperature
* Temperature of back plate of fridge (possibly to some day prevent icing up when crashing beers?)

I'm not sure how to go about this, though. Obviously these have relation to the firmware - perhaps this is possible by making "temperature probes" an entity you create for a Device, and giving each "temperature probe" a "role" property that corresponds to the current `BeerTemp` etc. namings that you can then select?

### CODE REVIEW

**Comment by thorrak** [comment]
Without checking the 0.5.5 firmware, I'm assuming that the additional functions (`Log1Temp`, `Log2Temp`, etc.) are just additional [device functions](https://github.com/thorrak/brewpi-esp8266/blob/5db84ebf94ff08799a513ca191f573a74b829e5f/legacy-platformio/src/EepromStructs.h#L66) that can be assigned to sensors. Assuming that's the case I think the trick really is just deciding how best to have the data logged by brewpi-script (and subsequently handling the display in Fermentrack). 

Fermentrack itself is relatively ignorant of the sensors/configuration on the device, as Fermentrack loads/manages it only when necessary (i.e. when attempting to configure a sensor/device). BrewPi-script on the other hand looks out for reading specifically associated with the `DEVICE_BEER_TEMP` and `DEVICE_FRIDGE_TEMP` device functions and writes these values directly to the CSV log files. 

There's already precedent to [modifying the log format](https://github.com/thorrak/fermentrack/blob/master/app/models.py#L1276) in BrewPi-script with the addition of the specific gravity sensor data to the log files. In that sense, simply tacking on an additional column or three should be easy enough. The trick is going to be storing the metadata associated with the sensor to know what devices were present when the currently active beer log was started.

**Comment by NamelessCoder** [comment]
> I would actually recommend adding all three of the sensors, similar to what was done in the official script repo:

Sounds like the right choice. Logging them is of course step one - then we can perhaps figure out a solution for metadata that would allow defining which of these should act as "room temp" since that has a special place in the UI.

I've been thinking that RRD might work here for logging the sensor values, states and such. I first came across it a long time ago via https://oss.oetiker.ch/rrdtool/ - a single file could be used to keep a permanent and always running collection of all sensor values without ever growing in size. It could then be made possible to export a CSV or other format log file based on one or more columns from the RRD. Point would be that sensor collection could happen constantly regardless of logging being enabled, so we would see graphed values as soon as things are set up - and would preserve graph history when switching to a different beer (because beer start/stop would just be annotations that tag a time stamp). Just a thought, and ever so slightly off topic but not really...

**Comment by thorrak** [comment]
I merged this into the "modern" branch (I'll make a comment elsewhere on what that is) - leaving this pull request open for now as part of the discussion around the other temp sensor types

**Comment by thorrak** [comment]
This was merged into the "modern" branch (which will be merged into dev/master in the coming weeks). Closing the pull request.

**Pull request closed without merging**
